In [44]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [45]:
ticket = pd.read_csv('ticket.csv')

In [46]:
ticket.head()

,orderid,cashier,saledate,total,customerid,ticketcode,date,time,slot,room,film,slot type,ticket type,ticket price,popcorn
0,10006052019B0225,emp002,5/6/2019,90000.0,0000000014,20074925,5/6/2019,18:15,G04,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
1,10006052019B0225,emp002,5/6/2019,90000.0,0000000014,20074924,5/6/2019,18:15,G03,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
2,10022052019B0167,emp011,5/22/2019,90000.0,0000000034,20097042,5/22/2019,20:45,E04,2,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
3,10022052019B0167,emp011,5/22/2019,90000.0,0000000034,20097041,5/22/2019,20:45,E03,2,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
4,10130052019B0141,emp005,5/30/2019,90000.0,0000000034,20106761,5/30/2019,19:30,F04,1,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Không

In [47]:
ticket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35474 entries, 0 to 35473
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   orderid       35378 non-null  object
 1   cashier       35474 non-null  object
 2   saledate      35378 non-null  object
 3   total         35378 non-null  float64
 4   customerid    35474 non-null  object
 5   ticketcode    35474 non-null  int64
 6   date          35474 non-null  object
 7   time          35474 non-null  object
 8   slot          35474 non-null  object
 9   room          35474 non-null  int64
 10  film          35474 non-null  object
 11  slot type     35474 non-null  object
 12  ticket type   35474 non-null  object
 13  ticket price  35474 non-null  int64
 14  popcorn       35378 non-null  object
dtypes: float64(1), int64(3), object(11)
memory usage: 4.1+ MB

In [48]:
ticket.describe(include='object')

,orderid,cashier,saledate,customerid,date,time,slot,film,slot type,ticket type,popcorn
count,35378,35474,35378,35474,35474,35474,35474,35474,35474,35474,35378
unique,14598,16,30,4479,30,159,190,19,2,1,2
top,10026052019B0285,emp011,5/11/2019,KH6166700,5/11/2019,19:15,G09,MẸ MA THAN KHÓC LA LLORONA (C18),ĐƠN,Thành viên,Không
freq,43,5894,2094,10132,2094,1583,597,9630,34063,35474,35287

In [49]:
ticket.isnull().sum()

orderid         96
cashier          0
saledate        96
total           96
customerid       0
ticketcode       0
date             0
time             0
slot             0
room             0
film             0
slot type        0
ticket type      0
ticket price     0
popcorn         96
dtype: int64

In [50]:
ticket.shape

#Before dropping rows with NaN values

(35474, 15)

In [51]:
ticket.dropna(inplace=True, axis=0)

In [52]:
ticket.shape

#After dropping rows with NaN values

(35378, 15)

In [53]:
ticket[['orderid', 'cashier', 'saledate', 'date', 'customerid', 'time']].drop_duplicates()['customerid'].value_counts()

#The frequency of customers going to cinema

customerid
KH6166700          4045
0000029127         2856
0001121703          206
0003004563           19
KH3742976            18
                   ...
0001081290            1
0001081341            1
0001081348            1
0001081361            1
WEBS00000046015       1
Name: count, Length: 4451, dtype: int64

In [54]:
ticket[ticket['ticket price']<=0]

# Outlier

,orderid,cashier,saledate,total,customerid,ticketcode,date,time,slot,room,film,slot type,ticket type,ticket price,popcorn
7327,10126052019B0123,emp010,5/26/2019,90000.0,0000029127,20102169,5/26/2019,17:25,D11,4,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,0,Có

In [55]:
check = ticket.groupby(by='orderid')['total'].mean() - ticket.groupby('orderid')['ticket price'].sum()

#Check if there are any difference between the total cost of each order ID and the sum of all ticket price

In [56]:
check[check!=0]

#These differences might be due to the popcorn price. However, why are there negative values ?

orderid
10005052019B0017    -10000.0
10006052019B0304     45000.0
10006052019B0305     45000.0
10009052019B0316     -5000.0
10013052019B0163     45000.0
10019052019B0304     45000.0
10019052019B0305     45000.0
10020052019B0075    -90000.0
10026052019B0063    225000.0
10027052019B0223     45000.0
10028052019B0057     45000.0
10029052019B0012     45000.0
10030052019B0068     45000.0
10101052019B0072    225000.0
10108052019B0139     45000.0
10108052019B0165     45000.0
10109052019B0101     -5000.0
10111052019B0123     45000.0
10115052019B0108     45000.0
12505052019B0026     90000.0
12515052019B0024     90000.0
dtype: float64

In [57]:
check_false = check[check!=0].index

In [58]:
ticket[np.logical_and(ticket['orderid'].isin(check_false), ticket['popcorn']!='Có')]

# We can conclude that all differences in the prices are results of purchasing popcorn

Empty DataFrame
Columns: [orderid, cashier, saledate, total, customerid, ticketcode, date, time, slot, room, film, slot type, ticket type, ticket price, popcorn]
Index: []

In [59]:
popcorn_purchase = list(ticket[ticket['popcorn']=='Có']['orderid'].unique())

# List of people who purchased popcorn

In [60]:
wrong_total_id = []

for id in popcorn_purchase:
    if id not in check[check!=0].index:
        wrong_total_id.append(id)
        
for id, value in check.items():
    if value!=0 and id not in popcorn_purchase:
        wrong_total_id.append(id)

#Listing miscalculation and popcorn

In [61]:
ticket[ticket['orderid'].isin(wrong_total_id)]

,orderid,cashier,saledate,total,customerid,ticketcode,date,time,slot,room,film,slot type,ticket type,ticket price,popcorn
3458,12502052019B0013,emp010,5/2/2019,135000.0,0000029127,20071475,5/2/2019,19:05,J07,1,AVENGERS: HỒI KẾT,ĐÔI,Thành viên,90000,Có
3461,12502052019B0013,emp010,5/2/2019,135000.0,0000029127,20071474,5/2/2019,19:05,E13,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Có
3945,10009052019B0239,emp008,5/9/2019,405000.0,0000029127,20078926,5/9/2019,17:00,I04,1,LẬT MẶT: NHÀ CÓ KHÁCH,ĐƠN,Thành viên,45000,Có
3946,10009052019B0239,emp008,5/9/2019,405000.0,0000029127,20078923,5/9/2019,17:00,I01,1,LẬT MẶT: NHÀ CÓ KHÁCH,ĐƠN,Thành viên,45000,Có
3947,10009052019B0239,emp008,5/9/2019,405000.0,0000029127,20078925,5/9/2019,17:00,I03,1,LẬT MẶT: NHÀ CÓ KHÁCH,ĐƠN,Thành viên,45000,Có
3948,10009052019B0239,emp008,5/9/2019,405000.0,0000029127,20078928,5/9/2019,17:00,I06,1,LẬT MẶT: NHÀ CÓ KHÁCH,ĐƠN,Thành viên,45000,Có
3951,10009052019B0239,emp008,5/9/2019,405000.0,0000029127,20078930,5/9/2019,17:00,J02,1,LẬT MẶT: NHÀ CÓ KHÁCH,ĐÔI,Thành viên,90000,Có
3952,10009052019B0239,emp008,5/9/2019,405000.0,0000029127,20078924,5/9/2019,17:00,I02,1,LẬT MẶT: NHÀ CÓ KHÁCH,ĐƠN,Thành viên,45000,Có
3954,10009052019B0239,emp008,5/9/2019,405000.0,0000029127,20078929,5/9/2019,17:00,I07,1,LẬT MẶT: NHÀ CÓ KHÁCH,ĐƠN,Thành viên,45000,Có
3955,10009052019B0239,emp008,5/9/2019,405000.0,0000029127,20078927,5/9/2019,17:00,I05,1,LẬT MẶT: NHÀ CÓ KHÁCH,ĐƠN,Thành viên,45000,Có
4510,12508052019B0045,emp007,5/8/2019,135000.0,0000029127,20077900,5/8/2019,20:35,G17,2,MẸ MA THAN KHÓC LA LLORONA (C18),ĐƠN,Thành viên,45000,Có
4511,12508052019B0045,emp007,5/8/2019,135000.0,0000029127,20077901,5/8/2019,20:35,H09,2,MẸ MA THAN KHÓC LA LLORONA (C18),ĐÔI,Thành viên,90000,Có
6228,10127052019B0074,emp008,5/27/2019,135000.0,0000029127,20103834,5/27/2019,20:20,G14,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Có
6229,10127052019B0074,emp008,5/27/2019,135000.0,0000029127,20103835,5/27/2019,20:20,H07,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐÔI,Thành viên,90000,Có
7321,10126052019B0123,emp010,5/26/2019,90000.0,0000029127,20102170,5/26/2019,17:25,D12,4,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Có
7326,10126052019B0123,emp010,5/26/2019,90000.0,0000029127,20102168,5/26/2019,17:25,D10,4,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Có
7327,10126052019B0123,emp010,5/26/2019,90000.0,0000029127,20102169,5/26/2019,17:25,D11,4,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,0,Có
7398,10027052019B0198,emp005,5/27/2019,135000.0,0000029127,20103625,5/27/2019,19:30,J01,1,(LT) DORAEMON: NOBITA VÀ MẶT TRĂNG PHIÊU LƯU K...,ĐÔI,Thành viên,90000,Có
7399,10027052019B0198,emp005,5/27/2019,135000.0,0000029127,20103624,5/27/2019,19:30,I01,1,(LT) DORAEMON: NOBITA VÀ MẶT TRĂNG PHIÊU LƯU K...,ĐƠN,Thành viên,45000,Có
15980,10128052019B0095,emp005,5/28/2019,450000.0,0001121703,20104542,5/28/2019,20:20,H05,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐÔI,Thành viên,90000,Có
15981,10128052019B0095,emp005,5/28/2019,450000.0,0001121703,20104536,5/28/2019,20:20,G07,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Có
15982,10128052019B0095,emp005,5/28/2019,450000.0,0001121703,20104537,5/28/2019,20:20,G08,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Có
15983,10128052019B0095,emp005,5/28/2019,450000.0,0001121703,20104540,5/28/2019,20:20,G11,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Có
15984,10128052019B0095,emp005,5/28/2019,450000.0,0001121703,20104539,5/28/2019,20:20,G10,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Có
15985,10128052019B0095,emp005,5/28/2019,450000.0,0001121703,20104538,5/28/2019,20:20,G09,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Có
15986,10128052019B0095,emp005,5/28/2019,450000.0,0001121703,20104541,5/28/2019,20:20,G12,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Có
15987,10128052019B0095,emp005,5/28/2019,450000.0,0001121703,20104535,5/28/2019,20:20,F12,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Có
15988,10128052019B0095,emp005,5/28/2019,450000.0,0001121703,20104534,5/28/2019,20:20,F11,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Có
20455,12512052019B0042,emp005,5/12/2019,180000.0,0001167369,20085012,5/12/2019,18:31,G14,2,POKÉMON: THÁM TỬ PIKACHU (C13),ĐƠN,Thành viên,45000,Có
20456,12512052019B0042,emp005,5/12/2019,180000.0,0001167369,20085014,5/12/2019,18:31,H07,2,POKÉMON: THÁM TỬ PIKACHU (C13),ĐÔI,Thành viên,90000,Có
20457,12512052019B0042,emp005,5/12/2019,180000.0,0001167369,20085013,5/12/2019,18:31,G15,2,POKÉMON: THÁM TỬ PIKACHU (C13),ĐƠN,Thành viên,45000,Có
22955,10118052019B0156,emp008,5/18/2019,135000.0,0003008088,20092447,5/18/2019,18:40,J01,1,POKÉMON: THÁM TỬ PIKACHU (C13),ĐÔI,Thành viên,90000,Có
22956,10118052019B0156,emp008,5/18/2019,135000.0,0003008088,20092446,5/18/2019,18:40,I01,1,POKÉMON: THÁM TỬ PIKACHU (C13),ĐƠN,Thành viên,45000,Có
23411,12528052019B0025,emp008,5/28/2019,315000.0,0003009716,20104703,5/28/2019,19:30,I15,1,(LT) DORAEMON: NOBITA VÀ MẶT TRĂNG PHIÊU LƯU K...,ĐƠN,Thành viên,45000,Có
23412,12528052019B0025,emp008,5/28/2019,315000.0,0003009716,20104705,5/28/2019,19:30,J07,1,(LT) DORAEMON: NOBITA VÀ MẶT TRĂNG PHIÊU LƯU K...,ĐÔI,Thành viên,90000,Có
23413,12528052019B0025,emp008,5/28/2019,315000.0,0003009716,20104704,5/28/2019,19:30,J06,1,(LT) DORAEMON: NOBITA VÀ MẶT TRĂNG PHIÊU LƯU K...,ĐÔI,Thành viên,90000,Có
23414,12528052019B0025,emp008,5/28/2019,315000.0,0003009716,20104706,5/28/2019,19:30,J08,1,(LT) DORAEMON: NOBITA VÀ MẶT TRĂNG PHIÊU LƯU K...,ĐÔI,Thành viên,90000,Có
25680,10019052019B0280,emp012,5/19/2019,180000.0,KH6166700,20093962,5/19/2019,18:40,D15,1,POKÉMON: THÁM TỬ PIKACHU (C13),ĐƠN,Thành viên,45000,Có
25681,10019052019B0280,emp012,5/19/2019,180000.0,KH6166700,20093963,5/19/2019,18:40,D16,1,POKÉMON: THÁM TỬ PIKACHU (C13),ĐƠN,Thành viên,45000,Có
25682,10019052019B0280,emp012,5/19/2019,180000.0,KH6166700,20093964,5/19/2019,18:40,J09,1,POKÉMON: THÁM TỬ PIKACHU (C13),ĐÔI,Thành viên,90000,Có
28335,10124052019B0059,emp011,5/24/2019,405000.0,KH6166700,20099113,5/24/2019,18:30,G13,2,VÔ GIAN ĐẠO (C18),ĐƠN,Thành viên,45000,Có
28336,10124052019B0059,emp011,5/24/2019,405000.0,KH6166700,20099116,5/24/2019,18:30,H07,2,VÔ GIAN ĐẠO (C18),ĐÔI,Thành viên,90000,Có
28337,10124052019B0059,emp011,5/24/2019,405000.0,KH6166700,20099115,5/24/2019,18:30,G15,2,VÔ GIAN ĐẠO (C18),ĐƠN,Thành viên,45000,Có
28338,10124052019B0059,emp011,5/24/2019,405000.0,KH6166700,20099117,5/24/2019,18:30,H09,2,VÔ GIAN ĐẠO (C18),ĐÔI,Thành viên,90000,Có
28339,10124052019B0059,emp011,5/24/2019,405000.0,KH6166700,20099114,5/24/2019,18:30,G14,2,VÔ GIAN ĐẠO (C18),ĐƠN,Thành viên,45000,Có
28340,10124052019B0059,emp011,5/24/2019,405000.0,KH6166700,20099112,5/24/2019,18:30,G12,2,VÔ GIAN ĐẠO (C18),ĐƠN,Thành viên,45000,Có
28341,10124052019B0059,emp011,5/24/2019,405000.0,KH6166700,20099111,5/24/2019,18:30,G11,2,VÔ GIAN ĐẠO (C18),ĐƠN,Thành viên,45000,Có
30233,10113052019B0124,emp012,5/13/2019,135000.0,KH6166700,20086577,5/13/2019,20:20,H09,2,MẸ MA THAN KHÓC LA LLORONA (C18),ĐÔI,Thành viên,90000,Có
30234,10113052019B0124,emp012,5/13/2019,135000.0,KH6166700,20086576,5/13/2019,20:20,G17,2,MẸ MA THAN KHÓC LA LLORONA (C18),ĐƠN,Thành viên,45000,Có
33311,10112052019B0109,emp011,5/12/2019,135000.0,KH6166700,20084137,5/12/2019,14:40,G07,2,MẸ MA THAN KHÓC LA LLORONA (C18),ĐƠN,Thành viên,45000,Có
33312,10112052019B0109,emp011,5/12/2019,135000.0,KH6166700,20084138,5/12/2019,14:40,H04,2,MẸ MA THAN KHÓC LA LLORONA (C18),ĐÔI,Thành viên,90000,Có
34550,10005052019B0417,emp007,5/5/2019,180000.0,KH6166700,20074114,5/5/2019,20:50,G13,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Có
34551,10005052019B0417,emp007,5/5/2019,180000.0,KH6166700,20074116,5/5/2019,20:50,J05,1,AVENGERS: HỒI KẾT,ĐÔI,Thành viên,90000,Có
34552,10005052019B0417,emp007,5/5/2019,180000.0,KH6166700,20074115,5/5/2019,20:50,G14,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Có

In [62]:
wrong_cashier = ticket[ticket['orderid'].isin(check_false)][['orderid', 'cashier']].drop_duplicates()['cashier'].value_counts()

In [63]:
wrong_cashier

cashier
emp006    5
emp007    3
emp012    3
emp004    2
emp011    2
emp001    1
emp005    1
emp015    1
emp008    1
emp014    1
emp002    1
Name: count, dtype: int64

In [64]:
ticket['time'].unique()

array(['18:15', '20:45', '19:30', '19:40', '14:00', '20:50', '13:40',
       '15:00', '20:20', '22:40', '22:30', '18:10', '12:40', '19:35',
       '16:40', '19:15', '19:00', '18:30', '17:25', '16:30', '20:15',
       '10:45', '15:40', '13:25', '12:45', '15:20', '14:45', '15:10',
       '16:45', '17:50', '13:10', '13:00', '12:10', '13:35', '19:50',
       '12:30', '20:35', '14:35', '22:15', '9:00', '21:40', '10:30',
       '10:55', '19:45', '18:00', '21:30', '12:20', '17:20', '10:40',
       '18:40', '15:05', '17:00', '9:30', '13:45', '8:55', '10:20',
       '14:20', '9:15', '9:20', '14:25', '16:50', '18:35', '20:40',
       '9:10', '16:10', '16:15', '14:40', '19:05', '20:10', '8:40',
       '13:30', '18:25', '15:30', '17:10', '20:25', '15:25', '21:35',
       '12:35', '21:00', '19:20', '18:05', '11:45', '17:40', '16:00',
       '11:15', '14:50', '13:15', '13:05', '22:25', '17:15', '20:00',
       '13:20', '18:20', '10:50', '22:10', '15:15', '14:10', '17:35',
       '22:45', '17:45', '12:15', '21:20', '21:25', '22:20', '21:45',
       '20:30', '11:50', '8:29', '17:05', '22:05', '11:20', '15:01',
       '22:35', '13:50', '18:45', '8:45', '8:30', '11:10', '15:45',
       '14:15', '19:21', '12:55', '10:35', '14:46', '21:55', '17:30',
       '15:50', '11:05', '11:30', '10:00', '16:05', '23:00', '18:21',
       '18:31', '7:30', '12:39', '12:34', '16:20', '12:50', '11:01',
       '10:05', '14:05', '12:00', '8:49', '8:50', '8:35', '10:31',
       '11:25', '9:05', '11:00', '8:25', '12:05', '10:25', '10:15',
       '12:14', '21:05', '8:44', '23:15', '19:10'], dtype=object)