In [271]:
import pandas as pd 
import numpy as np

In [272]:
customer = pd.read_csv('customer.csv')

In [273]:
customer.head()

,customerid,DOB,gender,address,Website,job,industry
0,0000000014,36268,Nữ,hoa khe quan thanh khe,KH0104|0345,student,computer
1,0000000034,35901,Nam,man thai,KH0104|0333,student,health service
2,0000000051,34319,Nam,que son quang nam,KH0104|0255,blue collar,economics
3,0000000081,36472,Nam,truong chinh,KH0104|0293,student,economics
4,0000000098,34608,Nam,cẩm lệ,KH0104|40580,blue collar,health service

In [274]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4479 entries, 0 to 4478
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  4479 non-null   object
 1   DOB         4479 non-null   int64
 2   gender      4479 non-null   object
 3   address     4478 non-null   object
 4   Website     3943 non-null   object
 5   job         4479 non-null   object
 6   industry    3357 non-null   object
dtypes: int64(1), object(6)
memory usage: 245.1+ KB

In [276]:
from datetime import datetime, timedelta

In [277]:
current_date = datetime.now()
base_date = datetime(1899, 12, 30)
max_days_difference = (current_date - base_date).days

In [278]:
rows_to_drop = customer[customer['DOB']>max_days_difference].index

In [279]:
customer.drop(rows_to_drop, axis=0, inplace=True)

In [280]:
def date_convert(excel_date_value):
    base_date = datetime(1899, 12, 30)
    resulting_date = base_date + timedelta(days=excel_date_value)
    formatted_date = resulting_date.strftime('%d/%m/%Y')
    return formatted_date

customer['DOB'] = customer['DOB'].apply(date_convert)

In [281]:
customer['DOB'] = pd.to_datetime(customer['DOB'], format='%d/%m/%Y')

In [282]:
def age_calculate(birthdate):
    current_date = datetime.now()
    age = current_date.year - birthdate.year - ((current_date.month, current_date.day) < (birthdate.month, birthdate.day))
    return age 

customer['age'] = customer['DOB'].apply(age_calculate)

In [283]:
customer['age']

0       24
1       25
2       30
3       24
4       29
        ..
4474    28
4475    23
4476    35
4477    27
4478    21
Name: age, Length: 4475, dtype: int64

In [285]:
customer.nunique()

customerid    4475
DOB           3049
gender           2
address       1260
Website       3940
job              5
industry         9
age             50
dtype: int64

In [286]:
customer['gender'] = customer['gender'].astype('category')

In [287]:
customer['address'].value_counts()

address
hải châu                     312
ngũ hành sơn                 294
hòa khánh                    270
liên chiểu                   263
sơn trà                      252
                            ...
vũ quỳnh                       1
Pleiku, Gia Lai                1
Phan Boi                       1
 THÁI THỊ BÔI ĐÀ NẴNG          1
Thanh Khê Tây - Thanh Khê      1
Name: count, Length: 1260, dtype: int64

In [288]:
customer.isnull().sum()

customerid       0
DOB              0
gender           0
address          1
Website        535
job              0
industry      1118
age              0
dtype: int64

In [289]:
null_address_rows = customer[customer['address'].isnull()].index

In [290]:
customer.drop(null_address_rows, axis=0, inplace=True)

In [291]:

customer['address']

0                 hoa khe quan thanh khe
1                               man thai
2                      que son quang nam
3                           truong chinh
4                                 cẩm lệ
                      ...
4474    A, THUAN PHUOC,HAI CHAU, DA NANG
4475                        Phước Mỹ, ĐN
4476                   nguyen gian thanh
4477                        ngũ hành sơn
4478           Thanh Khê Tây - Thanh Khê
Name: address, Length: 4474, dtype: object

In [292]:
# import itertools
# from thefuzz import fuzz, process
# customer_address_id = customer[['customerid', 'address']]
# customer_address_id

In [293]:
# customer_address = customer["address"].apply(lambda x: x.lower())
# customer_address.value_counts()

In [294]:
# compare_address = pd.DataFrame(itertools.product(customer['customerid'], customer['customerid']), columns=['CSV 1', 'CSV 2'])
# compare_address

In [295]:
# compare_address = compare_address.merge(customer_address_id, how='right', left_on='CSV 1', right_on='customerid')
# compare_address = compare_address.merge(customer_address_id, how='right', left_on='CSV 2', right_on='customerid')
# compare_address

In [296]:
# compare_address = compare_address[['CSV 1', 'CSV 2', 'address_x', 'address_y']]
# compare_address

In [297]:
# partial_ratio_score = [fuzz.partial_ratio(c1, c2) for c1, c2 in compare_address[['address_x', 'address_y']].values]

In [298]:
# compare_address['Partial_ratio_score'] = partial_ratio_score
# compare_address

In [299]:
# compare_address = compare_address[compare_address['Partial_ratio_score'] >= 90]
# compare_address = compare_address[compare_address['CSV 1'] != compare_address['CSV 2']]
# compare_address

In [300]:
# compare_address.loc[compare_address['CSV 1']=='0001079961']

In [301]:
# compare_address

In [302]:
# compare_address[compare_address['Partial_ratio_score'] >= 80]

In [303]:
customer[customer['address'].apply(lambda x: len([part.strip() for part in x.replace(',', ' ').split()])==2)]['address'].unique()

array(['man thai', ' truong chinh', 'cẩm lệ', 'Tam Thuan', ' Le Duan',
       'Thuan Phuoc', 'liên chiểu', 'hòa vang', 'Ton Dan', ' thanh sơn',
       'hòa minh', 'sơn trà', 'THANH KHÊ', ' ton dan', 'hải châu',
       'Hùng Vương', 'hòa khánh', 'ĐỐNG ĐA', 'Mẹ Nhu', 'Nguyễn Chánh',
       ' Đống Đa', 'Văn Cao', 'lê duẩn', 'LIÊN CHIỂU', ' Lê Duẩn',
       'Phan Thanh', 'cam le', 'Lang Ha', 'tô hiệu', 'hỉa phòng',
       'Yên Khê', 'KHU đÔNG', 'đồng kì', 'Quảng Trị', 'Lê Thiệt',
       'LÊ DUẨN', 'hoaf vang', ' hùng vương', 'KHUÊ TRUNG', 'hoàng diệu',
       ' LÊ ĐỘ', 'tôn đản', 'quảng nam', 'bùi viện', 'TRƯỜNG CHINH',
       'quế sơn', 'Hoàng Diệu', ' Nguyễn Trãi', 'Đào Tần', 'Liên Chiểu',
       'Tôn Đản', 'lý triệu', 'Trần Phú', 'LÊ ĐỘ', 'Hàm Nghi', 'Hải Châu',
       'NGỌC HÂN', 'Quảng Nam', 'bac dau', 'tân thái', 'hải phòng',
       'Thanh thủy', 'Hải Phòng', 'Mân Quang', 'Huỳnh Lý', 'Hải Sơn',
       'Đỗ Quang', 'thanh Long', 'Thanh Thủy', 'KỲ ĐỒNG', 'HÙNG VƯƠNG',
       'cô giang', 'DUY TÂN', 'NGÔ QUYỀN', 'THANH DUYÊN', 'THÚC TỀ',
       'Quang Trung', 'HẢI PHÒNG', 'Lê Duẩn', ' TRƯỜNG CHINH', 'hội an',
       'quảng Ngãi', 'HÒA CHÂU', ' Yên Báy', 'BẮC ĐẨU', 'Ngô quyền',
       'an đồn', 'Thanh Hải', 'NGUYỄN NGHIÊM', 'phan thanh', 'Hoa Lien',
       'HÒA PHÁT', 'QUẢNG NAM', 'Đăk Lăk', 'Phan Thành', 'Trường Chinh',
       'Bình Định', 'Van Don', 'Hoa Minh', 'SON TRA', 'son tra',
       'lê duẫn', ' Phan Thanh', 'Hoa Son', 'Thôi Hữu', ' Sơn Trà',
       'TRường Sơn', 'núi thành', 'Hải Phong', 'Cao Thắng', 'tam kỳ',
       'nguyễn đăng', 'lê Duẩn', 'Mai An', 'Đống Đa', ' Hùng Vương',
       'Nguyễn Hoàng', 'PASRAUR, ĐN', ' HÙNG VƯƠNG', 'QUẢNG TRỊ',
       'Thế Lữ', ' TÔ HIỆU', 'thanh sơn', 'Thái phiên', 'nguyễn du',
       'Lê Lợi', 'HOÀNG DIỆU', ' Quang Trung', 'Hà SƠn', ' Thanh Thủy',
       'SƠN TRÀ', 'HẢI CHÂU', 'quãng nam', 'vũ quỳnh', 'NÚI THÀNH',
       'Phan Boi', 'HÀO VANG', 'TRẦN PHÚ', 'Quảng nam', 'QUANG RNAM',
       'QUẢNG BÌNH', 'Hòa Vang', 'THANH KHE', 'HAI CHAU', 'Chính Gián',
       'CẨM LỆ', 'CÂM LỆ', 'TAM KÌ', 'quang nam', 'Lê Cơ', '- BLO',
       'câẩm lệ', 'Thanh Khê', 'LIEN CHIEU', 'PHU YEN', ' ĐỐNG ĐA',
       'Ba Đình', ' Hải Phòng', 'HÒA VANG', 'CAM LE', 'Hai Phong',
       'hoaf khanhf', 'đại lộc', 'Hội An', 'thanh khê', 'Lê Độ', 'HỘI AN',
       'hai chau', 'Mai Am', 'Khúc Hạo', 'HOA VANG', 'q.liên chiểu',
       'hoi an', 'LIEN CHIÊU', 'THANH  KHÊ', 'Đổ Quang', 'Tran Phu',
       'QUANG NAM', 'Hà Tĩnh', 'QUANG NẢM', 'THẠC GIÁN', 'HÒA KHÁNH',
       'QUANG  NAM', 'SỢN TRÀ', ' Hải Phong', ' PHAN THANH', 'SƠN TRA',
       'quang trung', 'lê lai', 'QUANG TRI', ' HOÀNG DIỆU', 'HẢI DƯƠNG',
       'QUẢNG NMA', 'QUANG BINH', 'TAM KỲ', 'Quảng Bình', 'Phan thanh',
       'Duy Xuyên', 'Hòa An', 'Hòa Tiến', 'CẨM LÊH', 'Hòa Vang',
       ' THANH LONG', 'ĐĂK LĂK', 'TRƯƠNG ĐỊNH', ' Nam Cao', 'Vũ Hữu',
       'THNAH KHÊ', 'HÒA VNAG', ' lê duẩn', 'thanh thủy', 'QUANGR NAM',
       'LIEN CHIỂU', 'thanh khe', 'que son', ' Tôn Đản', 'quảng nam,',
       ' nguyễn trắc', 'hair chaau', 'bình định', 'Ngo Quyen', 'hà nội',
       'HÀ NỘI', 'KHÁNH HÒA', 'SƠN TRAG', 'SƠN TRTA', 'trần phú',
       'THĂNG BÌNH', 'LIEENC HIỂU', 'LIÊN CHIÊU', 'lang son', ' đỗ quang',
       ' Cach Mang', 'HOANG DIEU', 'thanh khee', 'KON TUM', 'đống đa',
       'ĐỖ NHUẬN', 'THANH KHEE', 'NGUYỄN HIỀN', 'Âu Cơ', 'sơn trà',
       'nghệ an', 'SƠN TRÀ', 'Kiên Giang', 'gia lai', 'nguyễn biểu',
       ' lê độ', 'hải Châu', 'QUẢNG Nam', 'Thanh Sơn', 'hà tĩnh',
       'Cô Giang', ' Trương Định', ' Lê Độ', ' Cao Thắng', 'tran phu',
       'LE DUAN', 'thi sách', 'HÀM NGHI', 'Nguyen Trai', 'tiểu la',
       'nguyễn hoàng', 'Nam Cao', 'Thi SÁch', 'trường chinh',
       ' NÚI THÀNH', 'hòa phong', 'An Khe', 'Cẩm Lệ', 'PHAN THANH',
       'KHUC HA', 'Bắc Sơn', 'BẮC GIANG', 'CO GIANG', 'quang binh',
       'BÌNH ĐỊNH', 'Quang Nam', 'CAO THẮNG', 'QUANG NGAI', 'Gia Lai',
       'HÒA THANH', 'QUANGC NGÃI', 'HÀ TĨNH', 'HÀN THUYÊN', 'THANH VINH',
       'quãng ngãi', 'ĐẠI LỘC', 'Ly Trien', ' LÊ DUẨN', 'HAF TINH',
       'Le Do', 'TÔN ĐẢN', 'Hà Nội', 'QUÃNG NAM', 'quảng ngãi',
       ' Trường Trinh', 'NGUYỄN HOÀNG', ' MAN THIÊNH', ' Cam Le-DN',
       'Quang Binh', 'Nguyen Hoang', 'Bắc Đẩu', ' Nui Thanh'],
      dtype=object)

In [304]:
from unidecode import unidecode

customer['address']=customer['address'].apply(unidecode).str.lower()
customer['address']=customer['address'].apply(lambda x: x.split('-')[-2] if '-' in x else x.split(',')[-2] if ',' in x else x)

In [305]:
customer['district'] = np.NaN
customer['city'] = np.NaN
customer['partial score'] = 0
customer

,customerid,DOB,gender,address,Website,job,industry,age,district,city,partial score
0,0000000014,1999-04-18,Nữ,hoa khe quan thanh khe,KH0104|0345,student,computer,24,NaN,NaN,0
1,0000000034,1998-04-16,Nam,man thai,KH0104|0333,student,health service,25,NaN,NaN,0
2,0000000051,1993-12-16,Nam,que son quang nam,KH0104|0255,blue collar,economics,30,NaN,NaN,0
3,0000000081,1999-11-08,Nam,truong chinh,KH0104|0293,student,economics,24,NaN,NaN,0
4,0000000098,1994-10-01,Nam,cam le,KH0104|40580,blue collar,health service,29,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...
4474,KH9855766,1995-07-05,Nữ,hai chau,NaN,specialist,finance,28,NaN,NaN,0
4475,KH9958204,2001-01-01,Nữ,phuoc my,NaN,teenager,NaN,23,NaN,NaN,0
4476,WEBS00000043900,1988-06-17,Nữ,nguyen gian thanh,KHWEBS|00006890,specialist,construction,35,NaN,NaN,0
4477,WEBS00000044909,1996-09-08,Nữ,ngu hanh son,KHWEBS|00007899,blue collar,finance,27,NaN,NaN,0
4478,WEBS00000046015,2002-04-26,Nữ,thanh khe tay,KHWEBS|00009005,teenager,NaN,21,NaN,NaN,0

In [306]:
customer.loc[customer['address']=='que son quang nam', 'partial score'].iloc[0]

0

In [307]:
from district_extract import get_district_list
from thefuzz import process

district_list = get_district_list()
district_list = list(map(unidecode, district_list))
district_list = list(map(str.lower, district_list))

unique_address = customer['address'].unique()
for district in district_list:
    matches=process.extract(district, unique_address, limit=len(unique_address))
    for match in matches:
        if match[1]>=88:
            if match[1]>customer.loc[customer['address']==match[0], 'partial score'].iloc[0]: 
                customer.loc[customer['address']==match[0], 'district']=district
                customer.loc[customer['address']==match[0], 'partial score']=match[1]

C:\Users\HP\AppData\Local\Temp\ipykernel_8808\3999776107.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'quan ba dinh' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  customer.loc[customer['address']==match[0], 'district']=district

In [308]:
from district_extract import get_district_dict

district_dict = get_district_dict()
print(district_dict)

{'quan ba dinh': 'Hà Nội', 'quan hoan kiem': 'Hà Nội', 'quan tay ho': 'Hà Nội', 'quan long bien': 'Hà Nội', 'quan cau giay': 'Hà Nội', 'quan dong da': 'Hà Nội', 'quan hai ba trung': 'Hà Nội', 'quan hoang mai': 'Hà Nội', 'quan thanh xuan': 'Hà Nội', 'huyen soc son': 'Hà Nội', 'huyen dong anh': 'Hà Nội', 'huyen gia lam': 'Hà Nội', 'quan nam tu liem': 'Hà Nội', 'huyen thanh tri': 'Sóc Trăng', 'quan bac tu liem': 'Hà Nội', 'huyen me linh': 'Hà Nội', 'quan ha dong': 'Hà Nội', 'thi xa son tay': 'Hà Nội', 'huyen ba vi': 'Hà Nội', 'huyen phuc tho': 'Hà Nội', 'huyen dan phuong': 'Hà Nội', 'huyen hoai duc': 'Hà Nội', 'huyen quoc oai': 'Hà Nội', 'huyen thach that': 'Hà Nội', 'huyen chuong my': 'Hà Nội', 'huyen thanh oai': 'Hà Nội', 'huyen thuong tin': 'Hà Nội', 'huyen phu xuyen': 'Hà Nội', 'huyen ung hoa': 'Hà Nội', 'huyen my duc': 'Hà Nội', 'thanh pho ha giang': 'Hà Giang', 'huyen dong van': 'Hà Giang', 'huyen meo vac': 'Hà Giang', 'huyen yen minh': 'Hà Giang', 'huyen quan ba': 'Hà Giang', 'huyen vi xuyen': 'Hà Giang', 'huyen bac me': 'Hà Giang', 'huyen hoang su phi': 'Hà Giang', 'huyen xin man': 'Hà Giang', 'huyen bac quang': 'Hà Giang', 'huyen quang binh': 'Hà Giang', 'thanh pho cao bang': 'Cao Bằng', 'huyen bao lam': 'Lâm Đồng', 'huyen bao lac': 'Cao Bằng', 'huyen ha quang': 'Cao Bằng', 'huyen trung khanh': 'Cao Bằng', 'huyen ha lang': 'Cao Bằng', 'huyen quang hoa': 'Cao Bằng', 'huyen hoa an': 'Cao Bằng', 'huyen nguyen binh': 'Cao Bằng', 'huyen thach an': 'Cao Bằng', 'thanh pho bac kan': 'Bắc Kạn', 'huyen pac nam': 'Bắc Kạn', 'huyen ba be': 'Bắc Kạn', 'huyen ngan son': 'Bắc Kạn', 'huyen bach thong': 'Bắc Kạn', 'huyen cho don': 'Bắc Kạn', 'huyen cho moi': 'An Giang', 'huyen na ri': 'Bắc Kạn', 'thanh pho tuyen quang': 'Tuyên Quang', 'huyen lam binh': 'Tuyên Quang', 'huyen na hang': 'Tuyên Quang', 'huyen chiem hoa': 'Tuyên Quang', 'huyen ham yen': 'Tuyên Quang', 'huyen yen son': 'Tuyên Quang', 'huyen son duong': 'Tuyên Quang', 'thanh pho lao cai': 'Lào Cai', 'huyen bat xat': 'Lào Cai', 'huyen muong khuong': 'Lào Cai', 'huyen si ma cai': 'Lào Cai', 'huyen bac ha': 'Lào Cai', 'huyen bao thang': 'Lào Cai', 'huyen bao yen': 'Lào Cai', 'thi xa sa pa': 'Lào Cai', 'huyen van ban': 'Lào Cai', 'thanh pho dien bien phu': 'Điện Biên', 'thi xa muong lay': 'Điện Biên', 'huyen muong nhe': 'Điện Biên', 'huyen muong cha': 'Điện Biên', 'huyen tua chua': 'Điện Biên', 'huyen tuan giao': 'Điện Biên', 'huyen dien bien': 'Điện Biên', 'huyen dien bien dong': 'Điện Biên', 'huyen muong ang': 'Điện Biên', 'huyen nam po': 'Điện Biên', 'thanh pho lai chau': 'Lai Châu', 'huyen tam duong': 'Vĩnh Phúc', 'huyen muong te': 'Lai Châu', 'huyen sin ho': 'Lai Châu', 'huyen phong tho': 'Lai Châu', 'huyen than uyen': 'Lai Châu', 'huyen tan uyen': 'Lai Châu', 'huyen nam nhun': 'Lai Châu', 'thanh pho son la': 'Sơn La', 'huyen quynh nhai': 'Sơn La', 'huyen thuan chau': 'Sơn La', 'huyen muong la': 'Sơn La', 'huyen bac yen': 'Sơn La', 'huyen phu yen': 'Sơn La', 'huyen moc chau': 'Sơn La', 'huyen yen chau': 'Sơn La', 'huyen mai son': 'Sơn La', 'huyen song ma': 'Sơn La', 'huyen sop cop': 'Sơn La', 'huyen van ho': 'Sơn La', 'thanh pho yen bai': 'Yên Bái', 'thi xa nghia lo': 'Yên Bái', 'huyen luc yen': 'Yên Bái', 'huyen van yen': 'Yên Bái', 'huyen mu cang chai': 'Yên Bái', 'huyen tran yen': 'Yên Bái', 'huyen tram tau': 'Yên Bái', 'huyen van chan': 'Yên Bái', 'huyen yen binh': 'Yên Bái', 'thanh pho hoa binh': 'Hòa Bình', 'huyen da bac': 'Hòa Bình', 'huyen luong son': 'Hòa Bình', 'huyen kim boi': 'Hòa Bình', 'huyen cao phong': 'Hòa Bình', 'huyen tan lac': 'Hòa Bình', 'huyen mai chau': 'Hòa Bình', 'huyen lac son': 'Hòa Bình', 'huyen yen thuy': 'Hòa Bình', 'huyen lac thuy': 'Hòa Bình', 'thanh pho thai nguyen': 'Thái Nguyên', 'thanh pho song cong': 'Thái Nguyên', 'huyen dinh hoa': 'Thái Nguyên', 'huyen phu luong': 'Thái Nguyên', 'huyen dong hy': 'Thái Nguyên', 'huyen vo nhai': 'Thái Nguyên', 'huyen dai tu': 'Thái Nguyên', 'thanh pho pho yen': 'Thái Nguyên', 'huyen phu binh': 'Thái Nguyên', 'thanh pho lang son': 'Lạng Sơn', 'huyen trang dinh': 'Lạng Sơn', 'huyen binh gia': 'Lạng Sơn', 'huyen van lang': 'Lạng Sơn', 'huyen cao loc': 'Lạng Sơn', 'huyen van quan': 'Lạng Sơn', 'huyen bac son': 'Lạng Sơn', 'huyen huu lung': 'Lạng Sơn', 'huyen chi lang': 'Lạng Sơn', 'huyen loc binh': 'Lạng Sơn', 'huyen dinh lap': 'Lạng Sơn', 'thanh pho ha long': 'Quảng Ninh', 'thanh pho mong cai': 'Quảng Ninh', 'thanh pho cam pha': 'Quảng Ninh', 'thanh pho uong bi': 'Quảng Ninh', 'huyen binh lieu': 'Quảng Ninh', 'huyen tien yen': 'Quảng Ninh', 'huyen dam ha': 'Quảng Ninh', 'huyen hai ha': 'Quảng Ninh', 'huyen ba che': 'Quảng Ninh', 'huyen van don': 'Quảng Ninh', 'thi xa dong trieu': 'Quảng Ninh', 'thi xa quang yen': 'Quảng Ninh', 'huyen co to': 'Quảng Ninh', 'thanh pho bac giang': 'Bắc Giang', 'huyen yen the': 'Bắc Giang', 'huyen tan yen': 'Bắc Giang', 'huyen lang giang': 'Bắc Giang', 'huyen luc nam': 'Bắc Giang', 'huyen luc ngan': 'Bắc Giang', 'huyen son dong': 'Bắc Giang', 'huyen yen dung': 'Bắc Giang', 'huyen viet yen': 'Bắc Giang', 'huyen hiep hoa': 'Bắc Giang', 'thanh pho viet tri': 'Phú Thọ', 'thi xa phu tho': 'Phú Thọ', 'huyen doan hung': 'Phú Thọ', 'huyen ha hoa': 'Phú Thọ', 'huyen thanh ba': 'Phú Thọ', 'huyen phu ninh': 'Quảng Nam', 'huyen yen lap': 'Phú Thọ', 'huyen cam khe': 'Phú Thọ', 'huyen tam nong': 'Đồng Tháp', 'huyen lam thao': 'Phú Thọ', 'huyen thanh son': 'Phú Thọ', 'huyen thanh thuy': 'Phú Thọ', 'huyen tan son': 'Phú Thọ', 'thanh pho vinh yen': 'Vĩnh Phúc', 'thanh pho phuc yen': 'Vĩnh Phúc', 'huyen lap thach': 'Vĩnh Phúc', 'huyen tam dao': 'Vĩnh Phúc', 'huyen binh xuyen': 'Vĩnh Phúc', 'huyen yen lac': 'Vĩnh Phúc', 'huyen vinh tuong': 'Vĩnh Phúc', 'huyen song lo': 'Vĩnh Phúc', 'thanh pho bac ninh': 'Bắc Ninh', 'huyen yen phong': 'Bắc Ninh', 'huyen que vo': 'Bắc Ninh', 'huyen tien du': 'Bắc Ninh', 'thanh pho tu son': 'Bắc Ninh', 'huyen thuan thanh': 'Bắc Ninh', 'huyen gia binh': 'Bắc Ninh', 'huyen luong tai': 'Bắc Ninh', 'thanh pho hai duong': 'Hải Dương', 'thanh pho chi linh': 'Hải Dương', 'huyen nam sach': 'Hải Dương', 'thi xa kinh mon': 'Hải Dương', 'huyen kim thanh': 'Hải Dương', 'huyen thanh ha': 'Hải Dương', 'huyen cam giang': 'Hải Dương', 'huyen binh giang': 'Hải Dương', 'huyen gia loc': 'Hải Dương', 'huyen tu ky': 'Hải Dương', 'huyen ninh giang': 'Hải Dương', 'huyen thanh mien': 'Hải Dương', 'quan hong bang': 'Hải Phòng', 'quan ngo quyen': 'Hải Phòng', 'quan le chan': 'Hải Phòng', 'quan hai an': 'Hải Phòng', 'quan kien an': 'Hải Phòng', 'quan do son': 'Hải Phòng', 'quan duong kinh': 'Hải Phòng', 'huyen thuy nguyen': 'Hải Phòng', 'huyen an duong': 'Hải Phòng', 'huyen an lao': 'Bình Định', 'huyen kien thuy': 'Hải Phòng', 'huyen tien lang': 'Hải Phòng', 'huyen vinh bao': 'Hải Phòng', 'huyen cat hai': 'Hải Phòng', 'huyen bach long vi': 'Hải Phòng', 'thanh pho hung yen': 'Hưng Yên', 'huyen van lam': 'Hưng Yên', 'huyen van giang': 'Hưng Yên', 'huyen yen my': 'Hưng Yên', 'thi xa my hao': 'Hưng Yên', 'huyen an thi': 'Hưng Yên', 'huyen khoai chau': 'Hưng Yên', 'huyen kim dong': 'Hưng Yên', 'huyen tien lu': 'Hưng Yên', 'huyen phu cu': 'Hưng Yên', 'thanh pho thai binh': 'Thái Bình', 'huyen quynh phu': 'Thái Bình', 'huyen hung ha': 'Thái Bình', 'huyen dong hung': 'Thái Bình', 'huyen thai thuy': 'Thái Bình', 'huyen tien hai': 'Thái Bình', 'huyen kien xuong': 'Thái Bình', 'huyen vu thu': 'Thái Bình', 'thanh pho phu ly': 'Hà Nam', 'thi xa duy tien': 'Hà Nam', 'huyen kim bang': 'Hà Nam', 'huyen thanh liem': 'Hà Nam', 'huyen binh luc': 'Hà Nam', 'huyen ly nhan': 'Hà Nam', 'thanh pho nam dinh': 'Nam Định', 'huyen my loc': 'Nam Định', 'huyen vu ban': 'Nam Định', 'huyen y yen': 'Nam Định', 'huyen nghia hung': 'Nam Định', 'huyen nam truc': 'Nam Định', 'huyen truc ninh': 'Nam Định', 'huyen xuan truong': 'Nam Định', 'huyen giao thuy': 'Nam Định', 'huyen hai hau': 'Nam Định', 'thanh pho ninh binh': 'Ninh Bình', 'thanh pho tam diep': 'Ninh Bình', 'huyen nho quan': 'Ninh Bình', 'huyen gia vien': 'Ninh Bình', 'huyen hoa lu': 'Ninh Bình', 'huyen yen khanh': 'Ninh Bình', 'huyen kim son': 'Ninh Bình', 'huyen yen mo': 'Ninh Bình', 'thanh pho thanh hoa': 'Thanh Hóa', 'thi xa bim son': 'Thanh Hóa', 'thanh pho sam son': 'Thanh Hóa', 'huyen muong lat': 'Thanh Hóa', 'huyen quan hoa': 'Thanh Hóa', 'huyen ba thuoc': 'Thanh Hóa', 'huyen quan son': 'Thanh Hóa', 'huyen lang chanh': 'Thanh Hóa', 'huyen ngoc lac': 'Thanh Hóa', 'huyen cam thuy': 'Thanh Hóa', 'huyen thach thanh': 'Thanh Hóa', 'huyen ha trung': 'Thanh Hóa', 'huyen vinh loc': 'Thanh Hóa', 'huyen yen dinh': 'Thanh Hóa', 'huyen tho xuan': 'Thanh Hóa', 'huyen thuong xuan': 'Thanh Hóa', 'huyen trieu son': 'Thanh Hóa', 'huyen thieu hoa': 'Thanh Hóa', 'huyen hoang hoa': 'Thanh Hóa', 'huyen hau loc': 'Thanh Hóa', 'huyen nga son': 'Thanh Hóa', 'huyen nhu xuan': 'Thanh Hóa', 'huyen nhu thanh': 'Thanh Hóa', 'huyen nong cong': 'Thanh Hóa', 'huyen dong son': 'Thanh Hóa', 'huyen quang xuong': 'Thanh Hóa', 'thi xa nghi son': 'Thanh Hóa', 'thanh pho vinh': 'Nghệ An', 'thi xa cua lo': 'Nghệ An', 'thi xa thai hoa': 'Nghệ An', 'huyen que phong': 'Nghệ An', 'huyen quy chau': 'Nghệ An', 'huyen ky son': 'Nghệ An', 'huyen tuong duong': 'Nghệ An', 'huyen nghia dan': 'Nghệ An', 'huyen quy hop': 'Nghệ An', 'huyen quynh luu': 'Nghệ An', 'huyen con cuong': 'Nghệ An', 'huyen tan ky': 'Nghệ An', 'huyen anh son': 'Nghệ An', 'huyen dien chau': 'Nghệ An', 'huyen yen thanh': 'Nghệ An', 'huyen do luong': 'Nghệ An', 'huyen thanh chuong': 'Nghệ An', 'huyen nghi loc': 'Nghệ An', 'huyen nam dan': 'Nghệ An', 'huyen hung nguyen': 'Nghệ An', 'thi xa hoang mai': 'Nghệ An', 'thanh pho ha tinh': 'Hà Tĩnh', 'thi xa hong linh': 'Hà Tĩnh', 'huyen huong son': 'Hà Tĩnh', 'huyen duc tho': 'Hà Tĩnh', 'huyen vu quang': 'Hà Tĩnh', 'huyen nghi xuan': 'Hà Tĩnh', 'huyen can loc': 'Hà Tĩnh', 'huyen huong khe': 'Hà Tĩnh', 'huyen thach ha': 'Hà Tĩnh', 'huyen cam xuyen': 'Hà Tĩnh', 'huyen ky anh': 'Hà Tĩnh', 'huyen loc ha': 'Hà Tĩnh', 'thi xa ky anh': 'Hà Tĩnh', 'thanh pho dong hoi': 'Quảng Bình', 'huyen minh hoa': 'Quảng Bình', 'huyen tuyen hoa': 'Quảng Bình', 'huyen quang trach': 'Quảng Bình', 'huyen bo trach': 'Quảng Bình', 'huyen quang ninh': 'Quảng Bình', 'huyen le thuy': 'Quảng Bình', 'thi xa ba don': 'Quảng Bình', 'thanh pho dong ha': 'Quảng Trị', 'thi xa quang tri': 'Quảng Trị', 'huyen vinh linh': 'Quảng Trị', 'huyen huong hoa': 'Quảng Trị', 'huyen gio linh': 'Quảng Trị', 'huyen da krong': 'Quảng Trị', 'huyen cam lo': 'Quảng Trị', 'huyen trieu phong': 'Quảng Trị', 'huyen hai lang': 'Quảng Trị', 'huyen con co': 'Quảng Trị', 'huyen phong dien': 'Cần Thơ', 'huyen quang dien': 'Thừa Thiên-Huế', 'huyen phu vang': 'Thừa Thiên-Huế', 'thi xa huong thuy': 'Thừa Thiên-Huế', 'thi xa huong tra': 'Thừa Thiên-Huế', 'huyen a luoi': 'Thừa Thiên-Huế', 'huyen phu loc': 'Thừa Thiên-Huế', 'huyen nam dong': 'Thừa Thiên-Huế', 'quan lien chieu': 'Đà Nẵng', 'quan thanh khe': 'Đà Nẵng', 'quan hai chau': 'Đà Nẵng', 'quan son tra': 'Đà Nẵng', 'quan ngu hanh son': 'Đà Nẵng', 'quan cam le': 'Đà Nẵng', 'huyen hoa vang': 'Đà Nẵng', 'huyen hoang sa': 'Đà Nẵng', 'thanh pho tam ky': 'Quảng Nam', 'thanh pho hoi an': 'Quảng Nam', 'huyen tay giang': 'Quảng Nam', 'huyen dong giang': 'Quảng Nam', 'huyen dai loc': 'Quảng Nam', 'thi xa dien ban': 'Quảng Nam', 'huyen duy xuyen': 'Quảng Nam', 'huyen que son': 'Quảng Nam', 'huyen nam giang': 'Quảng Nam', 'huyen phuoc son': 'Quảng Nam', 'huyen hiep duc': 'Quảng Nam', 'huyen thang binh': 'Quảng Nam', 'huyen tien phuoc': 'Quảng Nam', 'huyen bac tra my': 'Quảng Nam', 'huyen nam tra my': 'Quảng Nam', 'huyen nui thanh': 'Quảng Nam', 'huyen nong son': 'Quảng Nam', 'thanh pho quang ngai': 'Quảng Ngãi', 'huyen binh son': 'Quảng Ngãi', 'huyen tra bong': 'Quảng Ngãi', 'huyen son tinh': 'Quảng Ngãi', 'huyen tu nghia': 'Quảng Ngãi', 'huyen son ha': 'Quảng Ngãi', 'huyen son tay': 'Quảng Ngãi', 'huyen minh long': 'Quảng Ngãi', 'huyen nghia hanh': 'Quảng Ngãi', 'huyen mo duc': 'Quảng Ngãi', 'thi xa duc pho': 'Quảng Ngãi', 'huyen ba to': 'Quảng Ngãi', 'huyen ly son': 'Quảng Ngãi', 'thanh pho quy nhon': 'Bình Định', 'thi xa hoai nhon': 'Bình Định', 'huyen hoai an': 'Bình Định', 'huyen phu my': 'Bình Định', 'huyen vinh thanh': 'Cần Thơ', 'huyen tay son': 'Bình Định', 'huyen phu cat': 'Bình Định', 'thi xa an nhon': 'Bình Định', 'huyen tuy phuoc': 'Bình Định', 'huyen van canh': 'Bình Định', 'thanh pho tuy hoa': 'Phú Yên', 'thi xa song cau': 'Phú Yên', 'huyen dong xuan': 'Phú Yên', 'huyen tuy an': 'Phú Yên', 'huyen son hoa': 'Phú Yên', 'huyen song hinh': 'Phú Yên', 'huyen tay hoa': 'Phú Yên', 'huyen phu hoa': 'Phú Yên', 'thi xa dong hoa': 'Phú Yên', 'thanh pho nha trang': 'Khánh Hòa', 'thanh pho cam ranh': 'Khánh Hòa', 'huyen cam lam': 'Khánh Hòa', 'huyen van ninh': 'Khánh Hòa', 'thi xa ninh hoa': 'Khánh Hòa', 'huyen khanh vinh': 'Khánh Hòa', 'huyen dien khanh': 'Khánh Hòa', 'huyen khanh son': 'Khánh Hòa', 'huyen truong sa': 'Khánh Hòa', 'thanh pho phan rang-thap cham': 'Ninh Thuận', 'huyen bac ai': 'Ninh Thuận', 'huyen ninh son': 'Ninh Thuận', 'huyen ninh hai': 'Ninh Thuận', 'huyen ninh phuoc': 'Ninh Thuận', 'huyen thuan bac': 'Ninh Thuận', 'huyen thuan nam': 'Ninh Thuận', 'thanh pho phan thiet': 'Bình Thuận', 'thi xa la gi': 'Bình Thuận', 'huyen tuy phong': 'Bình Thuận', 'huyen bac binh': 'Bình Thuận', 'huyen ham thuan bac': 'Bình Thuận', 'huyen ham thuan nam': 'Bình Thuận', 'huyen tanh linh': 'Bình Thuận', 'huyen duc linh': 'Bình Thuận', 'huyen ham tan': 'Bình Thuận', 'huyen phu qui': 'Bình Thuận', 'thanh pho kon tum': 'Kon Tum', 'huyen dak glei': 'Kon Tum', 'huyen ngoc hoi': 'Kon Tum', 'huyen dak to': 'Kon Tum', 'huyen kon plong': 'Kon Tum', 'huyen kon ray': 'Kon Tum', 'huyen dak ha': 'Kon Tum', 'huyen sa thay': 'Kon Tum', 'huyen tu mo rong': 'Kon Tum', "huyen ia h' drai": 'Kon Tum', 'thanh pho pleiku': 'Gia Lai', 'thi xa an khe': 'Gia Lai', 'thi xa ayun pa': 'Gia Lai', 'huyen kbang': 'Gia Lai', 'huyen dak doa': 'Gia Lai', 'huyen chu pah': 'Gia Lai', 'huyen ia grai': 'Gia Lai', 'huyen mang yang': 'Gia Lai', 'huyen kong chro': 'Gia Lai', 'huyen duc co': 'Gia Lai', 'huyen chu prong': 'Gia Lai', 'huyen chu se': 'Gia Lai', 'huyen dak po': 'Gia Lai', 'huyen ia pa': 'Gia Lai', 'huyen krong pa': 'Gia Lai', 'huyen phu thien': 'Gia Lai', 'huyen chu puh': 'Gia Lai', 'thanh pho buon ma thuot': 'Đắk Lắk', 'thi xa buon ho': 'Đắk Lắk', "huyen ea h'leo": 'Đắk Lắk', 'huyen ea sup': 'Đắk Lắk', 'huyen buon don': 'Đắk Lắk', "huyen cu m'gar": 'Đắk Lắk', 'huyen krong buk': 'Đắk Lắk', 'huyen krong nang': 'Đắk Lắk', 'huyen ea kar': 'Đắk Lắk', "huyen m'drak": 'Đắk Lắk', 'huyen krong bong': 'Đắk Lắk', 'huyen krong pac': 'Đắk Lắk', 'huyen krong a na': 'Đắk Lắk', 'huyen lak': 'Đắk Lắk', 'huyen cu kuin': 'Đắk Lắk', 'thanh pho gia nghia': 'Đắk Nông', 'huyen dak glong': 'Đắk Nông', 'huyen cu jut': 'Đắk Nông', 'huyen dak mil': 'Đắk Nông', 'huyen krong no': 'Đắk Nông', 'huyen dak song': 'Đắk Nông', "huyen dak r'lap": 'Đắk Nông', 'huyen tuy duc': 'Đắk Nông', 'thanh pho da lat': 'Lâm Đồng', 'thanh pho bao loc': 'Lâm Đồng', 'huyen dam rong': 'Lâm Đồng', 'huyen lac duong': 'Lâm Đồng', 'huyen lam ha': 'Lâm Đồng', 'huyen don duong': 'Lâm Đồng', 'huyen duc trong': 'Lâm Đồng', 'huyen di linh': 'Lâm Đồng', 'huyen da huoai': 'Lâm Đồng', 'huyen da teh': 'Lâm Đồng', 'huyen cat tien': 'Lâm Đồng', 'thi xa phuoc long': 'Bình Phước', 'thanh pho dong xoai': 'Bình Phước', 'thi xa binh long': 'Bình Phước', 'huyen bu gia map': 'Bình Phước', 'huyen loc ninh': 'Bình Phước', 'huyen bu dop': 'Bình Phước', 'huyen hon quan': 'Bình Phước', 'huyen dong phu': 'Bình Phước', 'huyen bu dang': 'Bình Phước', 'huyen chon thanh': 'Bình Phước', 'huyen phu rieng': 'Bình Phước', 'thanh pho tay ninh': 'Tây Ninh', 'huyen tan bien': 'Tây Ninh', 'huyen tan chau': 'Tây Ninh', 'huyen duong minh chau': 'Tây Ninh', 'huyen chau thanh': 'Sóc Trăng', 'thi xa hoa thanh': 'Tây Ninh', 'huyen go dau': 'Tây Ninh', 'huyen ben cau': 'Tây Ninh', 'thi xa trang bang': 'Tây Ninh', 'thanh pho thu dau mot': 'Bình Dương', 'huyen bau bang': 'Bình Dương', 'huyen dau tieng': 'Bình Dương', 'thi xa ben cat': 'Bình Dương', 'huyen phu giao': 'Bình Dương', 'thi xa tan uyen': 'Bình Dương', 'thanh pho di an': 'Bình Dương', 'thanh pho thuan an': 'Bình Dương', 'huyen bac tan uyen': 'Bình Dương', 'thanh pho bien hoa': 'Đồng Nai', 'thanh pho long khanh': 'Đồng Nai', 'huyen tan phu': 'Đồng Nai', 'huyen vinh cuu': 'Đồng Nai', 'huyen dinh quan': 'Đồng Nai', 'huyen trang bom': 'Đồng Nai', 'huyen thong nhat': 'Đồng Nai', 'huyen cam my': 'Đồng Nai', 'huyen long thanh': 'Đồng Nai', 'huyen xuan loc': 'Đồng Nai', 'huyen nhon trach': 'Đồng Nai', 'thanh pho vung tau': 'Bà Rịa-Vũng Tàu', 'thanh pho ba ria': 'Bà Rịa-Vũng Tàu', 'huyen chau duc': 'Bà Rịa-Vũng Tàu', 'huyen xuyen moc': 'Bà Rịa-Vũng Tàu', 'huyen long dien': 'Bà Rịa-Vũng Tàu', 'huyen dat do': 'Bà Rịa-Vũng Tàu', 'thi xa phu my': 'Bà Rịa-Vũng Tàu', 'huyen con dao': 'Bà Rịa-Vũng Tàu', 'quan 1': 'Hồ Chí Minh', 'quan 12': 'Hồ Chí Minh', 'quan go vap': 'Hồ Chí Minh', 'quan binh thanh': 'Hồ Chí Minh', 'quan tan binh': 'Hồ Chí Minh', 'quan tan phu': 'Hồ Chí Minh', 'quan phu nhuan': 'Hồ Chí Minh', 'thanh pho thu duc': 'Hồ Chí Minh', 'quan 3': 'Hồ Chí Minh', 'quan 10': 'Hồ Chí Minh', 'quan 11': 'Hồ Chí Minh', 'quan 4': 'Hồ Chí Minh', 'quan 5': 'Hồ Chí Minh', 'quan 6': 'Hồ Chí Minh', 'quan 8': 'Hồ Chí Minh', 'quan binh tan': 'Hồ Chí Minh', 'quan 7': 'Hồ Chí Minh', 'huyen cu chi': 'Hồ Chí Minh', 'huyen hoc mon': 'Hồ Chí Minh', 'huyen binh chanh': 'Hồ Chí Minh', 'huyen nha be': 'Hồ Chí Minh', 'huyen can gio': 'Hồ Chí Minh', 'thanh pho tan an': 'Long An', 'thi xa kien tuong': 'Long An', 'huyen tan hung': 'Long An', 'huyen vinh hung': 'Long An', 'huyen moc hoa': 'Long An', 'huyen tan thanh': 'Long An', 'huyen thanh hoa': 'Long An', 'huyen duc hue': 'Long An', 'huyen duc hoa': 'Long An', 'huyen ben luc': 'Long An', 'huyen thu thua': 'Long An', 'huyen tan tru': 'Long An', 'huyen can duoc': 'Long An', 'huyen can giuoc': 'Long An', 'thanh pho my tho': 'Tiền Giang', 'thi xa go cong': 'Tiền Giang', 'thi xa cai lay': 'Tiền Giang', 'huyen tan phuoc': 'Tiền Giang', 'huyen cai be': 'Tiền Giang', 'huyen cai lay': 'Tiền Giang', 'huyen cho gao': 'Tiền Giang', 'huyen go cong tay': 'Tiền Giang', 'huyen go cong dong': 'Tiền Giang', 'huyen tan phu dong': 'Tiền Giang', 'thanh pho ben tre': 'Bến Tre', 'huyen cho lach': 'Bến Tre', 'huyen mo cay nam': 'Bến Tre', 'huyen giong trom': 'Bến Tre', 'huyen binh dai': 'Bến Tre', 'huyen ba tri': 'Bến Tre', 'huyen thanh phu': 'Bến Tre', 'huyen mo cay bac': 'Bến Tre', 'thanh pho tra vinh': 'Trà Vinh', 'huyen cang long': 'Trà Vinh', 'huyen cau ke': 'Trà Vinh', 'huyen tieu can': 'Trà Vinh', 'huyen cau ngang': 'Trà Vinh', 'huyen tra cu': 'Trà Vinh', 'huyen duyen hai': 'Trà Vinh', 'thi xa duyen hai': 'Trà Vinh', 'thanh pho vinh long': 'Vĩnh Long', 'huyen long ho': 'Vĩnh Long', 'huyen mang thit': 'Vĩnh Long', 'huyen vung liem': 'Vĩnh Long', 'huyen tam binh': 'Vĩnh Long', 'thi xa binh minh': 'Vĩnh Long', 'huyen tra on': 'Vĩnh Long', 'huyen binh tan': 'Vĩnh Long', 'thanh pho cao lanh': 'Đồng Tháp', 'thanh pho sa dec': 'Đồng Tháp', 'thanh pho hong ngu': 'Đồng Tháp', 'huyen tan hong': 'Đồng Tháp', 'huyen hong ngu': 'Đồng Tháp', 'huyen thap muoi': 'Đồng Tháp', 'huyen cao lanh': 'Đồng Tháp', 'huyen thanh binh': 'Đồng Tháp', 'huyen lap vo': 'Đồng Tháp', 'huyen lai vung': 'Đồng Tháp', 'thanh pho long xuyen': 'An Giang', 'thanh pho chau doc': 'An Giang', 'huyen an phu': 'An Giang', 'thi xa tan chau': 'An Giang', 'huyen phu tan': 'Cà Mau', 'huyen chau phu': 'An Giang', 'huyen tinh bien': 'An Giang', 'huyen tri ton': 'An Giang', 'huyen thoai son': 'An Giang', 'thanh pho rach gia': 'Kiên Giang', 'thanh pho ha tien': 'Kiên Giang', 'huyen kien luong': 'Kiên Giang', 'huyen hon dat': 'Kiên Giang', 'huyen tan hiep': 'Kiên Giang', 'huyen giong rieng': 'Kiên Giang', 'huyen go quao': 'Kiên Giang', 'huyen an bien': 'Kiên Giang', 'huyen an minh': 'Kiên Giang', 'huyen vinh thuan': 'Kiên Giang', 'thanh pho phu quoc': 'Kiên Giang', 'huyen kien hai': 'Kiên Giang', 'huyen u minh thuong': 'Kiên Giang', 

In [309]:
customer['city'] = customer['district'].apply(lambda x: district_dict.get(x, np.NaN))

In [310]:
customer.head(100)

,customerid,DOB,gender,address,Website,job,industry,age,district,city,partial score
0,0000000014,1999-04-18,Nữ,hoa khe quan thanh khe,KH0104|0345,student,computer,24,quan thanh khe,Đà Nẵng,90
1,0000000034,1998-04-16,Nam,man thai,KH0104|0333,student,health service,25,NaN,NaN,0
2,0000000051,1993-12-16,Nam,que son quang nam,KH0104|0255,blue collar,economics,30,NaN,NaN,0
3,0000000081,1999-11-08,Nam,truong chinh,KH0104|0293,student,economics,24,NaN,NaN,0
4,0000000098,1994-10-01,Nam,cam le,KH0104|40580,blue collar,health service,29,quan cam le,Đà Nẵng,90
...,...,...,...,...,...,...,...,...,...,...,...
95,0000010136,1992-12-11,Nam,hai chau,KH0104|18536,specialist,health service,31,quan hai chau,Đà Nẵng,90
96,0000010165,1994-02-17,Nữ,lien chieu,KH0104|18442,specialist,construction,29,quan lien chieu,Đà Nẵng,90
97,0000010196,1993-03-30,Nữ,hai phong da nang,KH0104|18241,blue collar,health service,30,NaN,NaN,0
98,0000010231,1996-02-03,Nam,son tra,KH0104|16066,blue collar,finance,27,quan son tra,Đà Nẵng,90
99,0000010241,1990-02-01,Nam,ngu hanh son,NaN,white collar,health service,33,quan ngu hanh son,Đà Nẵng,95

In [311]:
customer['district'].isna().sum()

1454

In [312]:
index = []
for address in unique_address:
    if ',' in address or '-' in address:
        index.append(list(customer[customer['address']==address].index)[0])

In [313]:
customer[customer.index.isin(index)]

Empty DataFrame
Columns: [customerid, DOB, gender, address, Website, job, industry, age, district, city, partial score]
Index: []

In [314]:
customer[customer.index.isin(index)]

Empty DataFrame
Columns: [customerid, DOB, gender, address, Website, job, industry, age, district, city, partial score]
Index: []

In [315]:
from district_extract import get_city_map, get_avenues_list, get_avenues_map

avenues_list = get_avenues_list()
avenues_map = get_avenues_map()
city_map = get_city_map()

unique_address = customer[customer['city'].isna()]['address'].unique()
for avenue in avenues_list:
    matches=process.extract(avenue, unique_address, limit=len(unique_address))
    for match in matches:
        if match[1]>=90:
            if match[1]>customer.loc[customer['address']==match[0], 'partial score'].iloc[0]: 
                customer.loc[customer['address']==match[0], 'city']='Đà Nẵng'
                customer.loc[customer['address']==match[0], 'district']=avenues_map[avenue]
                customer.loc[customer['address']==match[0], 'partial score']=match[1]

unique_address = customer[customer['city'].isna()]['address'].unique()
for city in city_map:
    matches=process.extract(city, unique_address, limit=len(unique_address))
    for match in matches:
        if match[1]>=90:
            if match[1]>customer.loc[customer['address']==match[0], 'partial score'].iloc[0]: 
                customer.loc[customer['address']==match[0], 'city']=city_map[city]
                customer.loc[customer['address']==match[0], 'partial score']=match[1]

In [316]:
customer['city'].isna().sum()

481

In [317]:
customer[np.logical_and(~customer['city'].isna(), customer['district'].isna())]

,customerid,DOB,gender,address,Website,job,industry,age,district,city,partial score
2,0000000051,1993-12-16,Nam,que son quang nam,KH0104|0255,blue collar,economics,30,NaN,Quảng Nam,90
187,0000012109,1993-07-20,Nam,ly thai to da nang,KH0104|22500,white collar,education,30,NaN,Đà Nẵng,90
224,0000013006,1991-02-01,Nữ,tran xuan le da nang,KH0104|1663,specialist,computer,32,NaN,Đà Nẵng,90
376,0000022793,1996-01-20,Nam,quang nam,KH0104|7918,blue collar,engineering,28,NaN,Quảng Nam,100
407,0000023511,1999-11-10,Nữ,paster da nang,KH0104|7045,student,computer,24,NaN,Đà Nẵng,90
...,...,...,...,...,...,...,...,...,...,...,...
4422,KH8557581,1991-08-01,Nữ,dien ban quang nam,NaN,white collar,health service,32,NaN,Quảng Nam,90
4431,KH8905897,1985-04-06,Nữ,quang nam,NaN,blue collar,government agent,38,NaN,Quảng Nam,100
4448,KH9304636,2001-08-08,Nam,dong ha quang tri,NaN,teenager,NaN,22,NaN,Quảng Trị,90
4451,KH937648,1995-05-17,Nam,ho chi minh,NaN,blue collar,social service,28,NaN,Hồ Chí Minh,100
4459,KH9605901,1998-07-08,Nam,quang nam,NaN,student,finance,25,NaN,Quảng Nam,100

In [318]:
customer[customer['city'].isna()]

,customerid,DOB,gender,address,Website,job,industry,age,district,city,partial score
9,0000000266,1995-01-01,Nam,le duan,KH0104|0044,blue collar,social service,29,NaN,NaN,0
14,0000000328,1994-03-28,Nam,le tan trung,NaN,blue collar,economics,29,NaN,NaN,0
15,0000000375,1995-03-20,Nam,le duy dinh,KH0104|9731,white collar,economics,28,NaN,NaN,0
20,0000000509,2002-10-28,Nữ,phan dinh phung,KH0104|0430,teenager,NaN,21,NaN,NaN,0
27,0000000659,1997-11-16,Nam,pham ngu lao,KH0104|1107,student,engineering,26,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...
4438,KH9142526,2000-04-21,Nữ,ha lam,NaN,teenager,NaN,23,NaN,NaN,0
4439,KH9143629,1998-08-22,Nữ,dung si thanh khe,NaN,student,economics,25,NaN,NaN,0
4443,KH9193438,2002-06-12,Nữ,le canh tuan,NaN,teenager,NaN,21,NaN,NaN,0
4457,KH9542382,2000-07-01,Nữ,bui xuan,NaN,teenager,NaN,23,NaN,NaN,0
4469,KH978498,1999-08-09,Nữ,dien loc,NaN,student,government agent,24,NaN,NaN,0

In [319]:
customer[~customer['district'].isna()].head(50)

,customerid,DOB,gender,address,Website,job,industry,age,district,city,partial score
0,0000000014,1999-04-18,Nữ,hoa khe quan thanh khe,KH0104|0345,student,computer,24,quan thanh khe,Đà Nẵng,90
1,0000000034,1998-04-16,Nam,man thai,KH0104|0333,student,health service,25,quan son tra,Đà Nẵng,100
3,0000000081,1999-11-08,Nam,truong chinh,KH0104|0293,student,economics,24,quan cam le,Đà Nẵng,100
4,0000000098,1994-10-01,Nam,cam le,KH0104|40580,blue collar,health service,29,quan cam le,Đà Nẵng,90
5,0000000109,1999-05-05,Nam,tam thuan,KH0104|0191,student,education,24,quan thanh khe,Đà Nẵng,100
6,0000000221.,1993-01-16,Nam,cam le,KH0104|2742,blue collar,construction,31,quan cam le,Đà Nẵng,90
7,0000000228,1995-11-09,Nam,ngu hanh son,NaN,specialist,health service,28,quan ngu hanh son,Đà Nẵng,95
8,0000000229,1992-01-14,Nam,le dinh duong,KH0104|2716,white collar,economics,32,quan hai chau,Đà Nẵng,100
10,0000000268,1996-12-07,Nam,trung nu vuong,KH0104|0182,blue collar,construction,27,quan hai chau,Đà Nẵng,100
11,0000000285,1992-07-29,Nữ,thuan phuoc,KH0104|0206,specialist,education,31,quan hai chau,Đà Nẵng,100
12,0000000297,1993-07-18,Nữ,ong ich khiem,KH0104|2750,specialist,education,30,quan hai chau,Đà Nẵng,100
13,0000000309,1996-03-04,Nữ,2 thang 9,KH0104|0172,blue collar,government agent,27,quan thanh khe,Đà Nẵng,100
16,0000000384,2002-11-22,Nữ,lien chieu,KH0104|19665,teenager,NaN,21,quan lien chieu,Đà Nẵng,90
17,0000000385,2002-12-02,Nữ,hoa vang,KH0104|20328,teenager,NaN,21,huyen hoa vang,Đà Nẵng,90
18,0000000415,1998-07-25,Nữ,ton dan,KH0104|0469,student,health service,25,quan cam le,Đà Nẵng,100
19,0000000502,1996-09-01,Nam,thanh son,KH0104|0402,blue collar,government agent,27,huyen thanh son,Phú Thọ,90
21,0000000541,1999-06-06,Nữ,dien bien phu,KH0104|0317,student,health service,24,thanh pho dien bien phu,Điện Biên,90
22,0000000558,1994-01-07,Nam,hoa minh,KH0104|0382,blue collar,finance,30,quan lien chieu,Đà Nẵng,100
23,0000000576,2016-01-11,Nam,son tra,KH0104|0519,teenager,NaN,8,quan son tra,Đà Nẵng,90
24,0000000591,1996-10-08,Nữ,hoa minh lien chieu,KH0104|0525,white collar,finance,27,quan lien chieu,Đà Nẵng,90
25,0000000622,1994-10-11,Nữ,le do thanh khe,KH0104|0993,white collar,computer,29,quan thanh khe,Đà Nẵng,90
26,0000000643,1997-07-24,Nữ,nguyen tri phuong,KH0104|1143,student,government agent,26,quan thanh khe,Đà Nẵng,100
28,0000000673,1999-12-19,Nam,tran cao van,KH0104|1125,student,social service,24,quan thanh khe,Đà Nẵng,100
29,0000000677,1986-11-13,Nam,trung nu vuong,KH0104|1121,white collar,social service,37,quan hai chau,Đà Nẵng,100
30,0000000685,1998-09-22,Nữ,trung nu vuong,KH0104|1078,student,government agent,25,quan hai chau,Đà Nẵng,100
32,0000000765,2000-09-21,Nữ,dien bien phu,KH0104|0047,teenager,NaN,23,thanh pho dien bien phu,Điện Biên,90
33,0000000777,1994-12-07,Nữ,thanh khe,NaN,specialist,economics,29,quan thanh khe,Đà Nẵng,90
34,0000000782,1998-04-17,Nữ,ton dan,KH0104|1089,student,economics,25,quan cam le,Đà Nẵng,100
36,0000000803,1996-08-15,Nữ,tran nhan tong,KH0104|14829,white collar,engineering,27,quan son tra,Đà Nẵng,100
37,0000000869,1994-05-12,Nữ,ngu hanh son,KH0104|16433,white collar,engineering,29,quan ngu hanh son,Đà Nẵng,95
38,0000000902,2003-03-24,Nữ,hai chau,KH0104|16581,teenager,NaN,20,quan hai chau,Đà Nẵng,90
39,0000000988,1992-02-01,Nam,lien chieu,KH0104|21044,white collar,construction,31,quan lien chieu,Đà Nẵng,90
40,0000000989,1999-01-29,Nữ,hung vuong,KH0104|8280,student,finance,24,quan thanh khe,Đà Nẵng,100
41,0000002231,1995-04-22,Nữ,ngu hanh son,KH0104|17248,specialist,engineering,28,quan ngu hanh son,Đà Nẵng,95
42,0000002296,1997-09-05,Nam,cam le,KH0104|17090,student,economics,26,quan cam le,Đà Nẵng,90
43,0000002299,1993-08-11,Nữ,lien chieu,KH0104|17103,specialist,construction,30,quan lien chieu,Đà Nẵng,90
44,0000002371,1999-11-24,Nữ,hoa khanh,KH0104|21160,student,finance,24,quan lien chieu,Đà Nẵng,95
45,0000002726,1997-12-13,Nữ,son tra,KH0104|16190,student,social service,26,quan son tra,Đà Nẵng,90
46,0000002739,1995-03-19,Nữ,hoa vang,KH0104|16196,blue collar,finance,28,huyen hoa vang,Đà Nẵng,90
47,0000002787,2001-11-18,Nữ,hoa khanh,KH0104|15969,teenager,NaN,22,quan lien chieu,Đà Nẵng,95
48,0000003204,2002-06-17,Nữ,hoa khanh,KH0104|14756,teenager,NaN,21,quan lien chieu,Đà Nẵng,95
49,0000003225,1992-01-01,Nam,ngu hanh son,NaN,blue collar,social service,32,quan ngu hanh son,Đà Nẵng,95
50,0000003228,1989-02-28,Nam,hoa khanh,KH0104|14837,specialist,engineering,34,quan lien chieu,Đà Nẵng,95
51,0000003244,2000-09-13,Nữ,lien chieu,KH0104|14754,teenager,NaN,23,quan lien chieu,Đà Nẵng,90
52,0000003254,1989-10-19,Nam,son tra,KH0104|14823,white collar,engineering,34,quan son tra,Đà Nẵng,90
53,0000003275,1989-12-03,Nam,lien chieu,KH0104|14743,specialist,economics,34,quan lien chieu,Đà Nẵng,90
54,0000003311,1999-08-24,Nữ,hoa khanh,KH0104|14904,student,education,24,quan lien chieu,Đà Nẵng,95
55,0000003335,2000-09-05,Nam,dong da,KH0104|14736,teenager,NaN,23,quan dong da,Hà Nội,90
56,0000003352,1992-02-29,Nam,hoa khanh,KH0104|14840,blue collar,education,31,quan lien chieu,Đà Nẵng,95
57,0000003363,1997-04-10,Nam,dong da,NaN,student,government agent,26,quan dong da,Hà Nội,90

In [320]:
district_map = {'quan lien chieu':'Quận liên chiều', 'quan hai chau':'Quận Hải Châu', 'quan ngu hanh son':'Quận Ngũ Hành Sơn', 'quan son tra':'Quận Sơn Trà', 'quan cam le':'Quận Cẩm Lệ', 'huyen hoa vang':'Huyện Hòa Vang', 'quan thanh khe':'Quận Thanh Khê'}

customer['district'] = customer['district'].map(district_map)

customer['district'].replace(to_replace={value: 'Others' for value in customer['district'].unique() if value not in district_map.values()}, inplace=True)

In [321]:
customer['district'].value_counts()

district
Others               906
Quận Hải Châu        773
Quận liên chiều      743
Quận Thanh Khê       539
Quận Sơn Trà         487
Quận Ngũ Hành Sơn    365
Quận Cẩm Lệ          363
Huyện Hòa Vang       298
Name: count, dtype: int64

In [322]:
customer

,customerid,DOB,gender,address,Website,job,industry,age,district,city,partial score
0,0000000014,1999-04-18,Nữ,hoa khe quan thanh khe,KH0104|0345,student,computer,24,Quận Thanh Khê,Đà Nẵng,90
1,0000000034,1998-04-16,Nam,man thai,KH0104|0333,student,health service,25,Quận Sơn Trà,Đà Nẵng,100
2,0000000051,1993-12-16,Nam,que son quang nam,KH0104|0255,blue collar,economics,30,Others,Quảng Nam,90
3,0000000081,1999-11-08,Nam,truong chinh,KH0104|0293,student,economics,24,Quận Cẩm Lệ,Đà Nẵng,100
4,0000000098,1994-10-01,Nam,cam le,KH0104|40580,blue collar,health service,29,Quận Cẩm Lệ,Đà Nẵng,90
...,...,...,...,...,...,...,...,...,...,...,...
4474,KH9855766,1995-07-05,Nữ,hai chau,NaN,specialist,finance,28,Quận Hải Châu,Đà Nẵng,90
4475,KH9958204,2001-01-01,Nữ,phuoc my,NaN,teenager,NaN,23,Quận Sơn Trà,Đà Nẵng,100
4476,WEBS00000043900,1988-06-17,Nữ,nguyen gian thanh,KHWEBS|00006890,specialist,construction,35,Others,Kiên Giang,88
4477,WEBS00000044909,1996-09-08,Nữ,ngu hanh son,KHWEBS|00007899,blue collar,finance,27,Quận Ngũ Hành Sơn,Đà Nẵng,95
4478,WEBS00000046015,2002-04-26,Nữ,thanh khe tay,KHWEBS|00009005,teenager,NaN,21,Quận Thanh Khê,Đà Nẵng,100

In [323]:
customer.drop(['partial score'], axis=1, inplace=True)

In [324]:
customer.set_index('customerid').to_csv('customer_cleaned.csv')